### PR TITLE
Test generation of reader on CI with multiple backends

### PR DESCRIPTION
**Pull request by lucafavatella**
Depends on PRs #9 and #12.

@alerque Do you by any chance know any projects having a `.travis.yml` installing SILE on Travis CI? I found the following refs but neither of them seem copy-pastable stuff: [ref1](https://github.com/simoncozens/sile#from-source) [ref2](https://github.com/simoncozens/sile/blob/master/.travis.yml)
At the moment it looks to me at least 2h of trial-and-error for getting SILE on Travis CI is needed. Help is welcome.

### CODE REVIEW

**Comment by alerque** [comment]
I can help get SILE running in Travis, yes. I'll look at this later.

Are you going for the new container infrastructure or the old full VM system?

**Comment by lucafavatella** [comment]
I would prefer container - it is cheaper for travis and faster for the user
- but if needed we can use sudo (that I understand being available only on
old infrastructure).

Thanks for looking at this.

**Comment by lucafavatella** [comment]
I understand this could be merged as it is - i.e. without SILE installed yet. So I removed "Work in Progress" from the title.

**Comment by jtauber** [comment]
I'll merge it and we can continue to improve / test with SILE

**Pull request merged**
