### PR TITLE
touchup outputs for better typesetting (both backends)

### PR DESCRIPTION
**Pull request by alerque**
See commit message(s) for more details. I may add a few more tweaks as well if you want to wait to merge, but I don't know when I'll get to it.

### CODE REVIEW

**Comment by jtauber** [comment]
should something be added to indicate that the glosses are English?

**Comment by alerque** [comment]
Hm. Yes actually technically that would be good to do. It won't matter as much since it's unlikely the footnotes will wrap, much less hyphenate so the fact that they are being processed with Greek rules is less egregious than that the main content was being processed as English, but it could still be set right and the PDF might as well end up correctly encoded. Why don't you leave this PR for a bit while I fiddle with that.

**Comment by jtauber** [comment]
In the LaTeX backend with double columns, wrapping is actually fairly common. 

Of courses the glosses might not be English (they could be any language) so it would be nice to eventually make the gloss language a command-line option.

**Comment by alerque** [comment]
I've corrected the output so that both backends are able to typeset the glosses with the features corresponding to their language. Default is English unless otherwise specified. My python foo is pretty weak sauce so if you want to implement this differently I'll understand, but this should at least demonstrate what needs to happen to the output.

Heaven help anybody that wants diglot footnotes. At this point only one additional language is supported.

**Comment by jtauber** [comment]
At first I was confused about the language map (rather than just passing in the language) but then I saw your note about SILE and LaTeX taking different language codes. sigh.

I still think it might be better for `--language` to just take the code native to the backend. Yes, that means you have to say `--language english --backend backends.LaTeX` vs `--language en --backend backends.SILE` but I think that is preferable to it not working at all if the language you want isn't in the map.

**Comment by alerque** [comment]
My two issues with that were:

1. This makes it obnoxiously hard to script comparisons between the two backends.
2. You can't even set a sensible default without more hackery. Either you need to check what the backend is and set different defaults (which is hard to document in, say, `--help`) or each backend needs to have it's own defaults (which moves the logic around and makes the main program inconsistent). Etc. Blah.

It's not hard to rip that out, but what would you think about keeping the implementation this way but returning English from the map function for unknown values to mitigate unsupported languages? Or is there a python library that can parse language names and return various forms?

**Comment by jtauber** [comment]
Ugh, you're right about the defaulting hack. Okay, let's leave it in. Is there a list somewhere of language names supported for LaTeX?

**Comment by alerque** [comment]
Yes. But you're going to wish you hadn't asked and had just merged my EN+TR version when you had the chance. See f5f7f8c.

While we're on the topic please allow me a small digression:

    $ git log --dif-filter=A -- languages
    commit o942df9bf
    Author: God <i@am>
    Reference: Genesis 11:7

       Not. Even. Joking.

**Comment by jtauber** [comment]
haha! my only criticism of the YAML file is that it forces the per-backend mappings to be in one place which breaks the plugability of backends.

**Comment by alerque** [comment]
How about this version? The code is slightly redundant as both backends are in one module file and could share some features, but I figured having them be as independent as possible might make an easier template for somebody to come along and extend or re-purpose. What do you think?

**Pull request merged**
